### ISSUE TITLE
Trip doesn't have serde Deserialize, Serialize traits

### ISSUE THREAD

**Issue by natawie** [rust-transit/gtfs-structure#130]

**Comment by Tristramg** [comment]
Thank you, I’ve made a pull request to fix it, but it might be a bit tricky because we use `Arc` there.

While you’re here, may I ask you how you use this crate, and maybe in which context?

**Comment by Tristramg** [comment]
It has been fixed, in the 0.32.3 release

**Comment by natawie** [comment]
> While you’re here, may I ask you how you use this crate, and maybe in which context?

whoops, didn't see this... sorry
don't know if you still want to know, but i use it for deserializing and then serializing stuff to bson to add it to a mongo db 'cuz actively having multiple cities' gtfs data in memory uses way too many resources

also, thanks for fixing this ^-^

**Comment by DomeQdev** [comment]
I also use this for deserializing and then serializing stuff to JSON to add it to a MongoDB

**Comment by Tristramg** [comment]
Perfect, so you are testing that the serialization works (we only used it to read it), nice!

I discover https://zbiorkom.live/warsaw, very cool (i like a lot the dynamic showing of a line with its realtime schedule)
