### ISSUE TITLE
from_zip missing

### ISSUE THREAD

**Issue by emma-k-alexandra** [rust-transit/gtfs-structure#48]
From the README:

>You can also directly read a zip file:
>
> ```rust 
> let gtfs = gtfs_structures::Gtfs::from_zip("path_of_a_zip")?;
>```

However, when attempting to use `from_zip`:
```rust
error[E0599]: no function or associated item named `from_zip` found for type `gtfs_structures::gtfs::Gtfs` in the current scope
 --> src/main.rs:4:28
  |
4 |     gtfs_structures::Gtfs::from_zip("~/Desktop/rail-gtfs-static.zip");
  |                            ^^^^^^^^ function or associated item not found in `gtfs_structures::gtfs::Gtfs`
```

using v0.16.1.

Looks like `from_zip` isn't present on `Gtfs`, and all tests use `from_path`.

**Comment by antoine-de** [comment]
oups I'm sorry we haven't updated the readme after some changes :roll_eyes: 

There is now a generic constructor `Gtfs::new` that will guess if it's a zip, a directory or an url (if you use the feature `read-url` (on by default)
