### ISSUE TITLE
route_color and route_text_color

### ISSUE THREAD

**Issue by paulswartz** [rust-transit/gtfs-structure#59]
Routes have two optional colors: `route_color` and `route_text_color`. I was thinking about parsing them into `Option<RGB>` structs, from https://crates.io/crates/rgb?

**Comment by antoine-de** [comment]
yep this crate seems lightweight, It seems ok for me.

At first glance I did not see a reader from hex string format, you might need to roll your own. You can check what they did in [transit model](https://github.com/CanalTP/transit_model/blob/master/src/objects.rs#L442).
