### ISSUE TITLE
Problem to read a remote GTFS

### ISSUE THREAD

**Issue by fchabouis** [rust-transit/gtfs-structure#78]
Hello,
I'm trying to use `from_url_async` with the following url : `https://www.itinisere.fr/fr/donnees-open-data/169/OpenData/Download?fileName=CG38.GTFS.zip`

I get the following error : 

```Err(Fetch(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.itinisere.fr")), port: None, path: "/fr/donnees-open-data/169/OpenData/Download", query: Some("fileName=CG38.GTFS.zip"), fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" } }) }))```

But I can download the file manually.

Any idea what could go wrong ?

My little test code :

```
#[tokio::main]
async fn main() {
    let url = "https://www.itinisere.fr/fr/donnees-open-data/169/OpenData/Download?fileName=CG38.GTFS.zip";
    let gtfs = gtfs_structures::RawGtfs::from_url_async(url).await;
    println!("{:?}", gtfs);
}
```

**Comment by Tristramg** [comment]
No answer yet, but we can first rule out some TLS negociation problems (my first idea). Using the blocking mode, it works fine, so it seems to be an async issue :scream: 

```
fn main() {
    let url = "https://www.itinisere.fr/fr/donnees-open-data/169/OpenData/Download?fileName=CG38.GTFS.zip";
    match gtfs_structures::RawGtfs::from_url(url) {
        Ok(gtfs) => println!("{:?}", gtfs.files),
        Err(e) => println!("{}", e),
    }
}
```
Works as expected

**Comment by Tristramg** [comment]
Right now your example code works (it didn’t either on my side). Maybe it actually was some temporary problem on the server’s side?

**Comment by fchabouis** [comment]
Hello Tristram,
Thank you for looking at this issue.
I've just launched both async and sync versions of the snippet, and I get the same error on both cases. Running you snippet yields `impossible to remotely access file`. Running mine, I get the same output as above.
There is possibly something going on the server side. But still, the file is accessible through the browser.

**Comment by Tristramg** [comment]
After investigating a bit more: the problem can be reproduced if there is no `reqwest="*"` in the Cargo.toml or if the version is different of the one in gtfs-structures (currently 0.10, but the behaviour is reproduced when bumpping to 0.11 on a local version of gtfs-structures).

This is really weird. As we put reqwest behind a feature flag, maybe we did something wrong and that a specific protocol feature is missing?

**Comment by Tristramg** [comment]
It seems when using the default tls it works. @antoine-de do you rember why choosing rust-tls ? couldn’t we maybe use the default options of reqwest?
